---

- name: create postgresql conf dir
  file:
    path: "{{ postgresql_conf }}"
    state: directory
    recurse: 'True'

- name: install postgresql-client-9.5
  package: name=postgresql-client-9.5

- name: create pass file
  lineinfile:
    path: /root/.pgpass
    regexp: ^"{{ item }}"
    line: "{{ item }}"
    create: 'True'
    mode: 0400
  with_items:
    - >
      "{{ postgresql_master }}:5432:replication:
      {{ postgresql_replica_user }}:
      {{ postgresql_replica_password }}"
- name: create a copy from master
  command: >
    "pg_basebackup -h {{ postgresql_master }}
     -D {{ postgresql_data }} -U {{ postgresql_replica_user }}
     -v -P -R -Xs"
  args:
    creates: /var/lib/postgresql
  notify:
    - copy conf

- name: create recovery file
  lineinfile:
    path: "{{ postgresql_data }}/recovery.conf"
    regexp: ^"{{ item.split('=')[0] }}"
    line: "{{ item }}"
    create: 'True'
  with_items:
    - standby_mode = on
    - >
      primary_conninfo = 'host={{ postgresql_master }}
       port=5432 user={{ postgresql_replica_user }}
       password={{ postgresql_replica_password }}'
    - restore_command = 'cp /var/lib/postgresql/9.5/main/archive/%f %p'
    - trigger_file = '/tmp/postgresql.trigger.5432'

- name: create postgres user
  user:
    name: postgres
    comment: "PostgreSQL administrator"
    shell: /bin/bash
    home: /var/lib/postgresql

- name: create postgres group
  group: name=postgres

- name: setup correct permission
  file:
    path: "{{ item }}"
    owner: postgres
    group: postgres
    recurse: 'True'
  with_items:
    - /var/lib/postgresql
    - /etc/postgresql
